name: Build CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
      - name: Install dependencies
        working-directory: ./mobile
        run: flutter pub get

      - name: Verify formatting
        working-directory: ./mobile
        run: dart format --output=none --set-exit-if-changed .

      - name: Generate files
        working-directory: ./mobile
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze project source
        working-directory: ./mobile
        run: flutter analyze --no-fatal-infos --no-fatal-warnings


      #- name: Run tests
      #  working-directory: ./mobile
      #  run: flutter test

      #- name: Run tests
      #  working-directory: ./app
      #  run: flutter test
